version: '3'
services:
  app:
    build: ./app
    image: go_redis_nginx/app
    container_name: app
    expose:
      - 8089
    links:
      - redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  nginx:
    build: ./nginx
    image: go_redis_nginx/nginx
    container_name: nginx
    ports:
      - 80:80
    links:
      - app
  redis:
    build: ./redis
    image: go_redis_nginx/redis
    container_name: redis
    expose:
      - 6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}