version: '3'
services:
  app:
    build: ./app
    image: go_redis_nginx/app
    container_name: app
    expose:
      - 8089
  nginx:
    build: ./nginx
    image: go_redis_nginx/nginx
    container_name: nginx
    ports:
      - 80:80
    links:
      - app